### ISSUE TITLE
[Question] How to show the calendar inline (always in the open state)?

### ISSUE THREAD

**Issue by christiankaindl** [wojtekmaj/react-datetimerange-picker#11]
I looked into the docs and found the `isCalendarOpen` prop. But, even when I set it to always `true` I can close it by clicking somewhere else: [Sample Codesandbox](https://codesandbox.io/s/datepicker-test-yxldh)

Is it possible to display the calendar in it's open state without it closing when the user clicks somewhere else?

---

_I mistakenly opened this issue on the react-calendar repo first. Leaving this just for future references: https://github.com/wojtekmaj/react-calendar/issues/230_

**Comment by wojtekmaj** [comment]
I definitely feel you. This is something I intend to change, this was a poor design choice to update internal state only on prop change. It'll need a major version bump.

Note to self: related to https://github.com/wojtekmaj/react-date-picker/issues/59

**Comment by wojtekmaj** [comment]
As a workaround, you could disable the calendar in React-DateTimeRange-Picker and just render it on the side, providing the same `value` and `onChange`.

**Comment by christiankaindl** [comment]
Thanks for the quick response and again for the suggestion to render a react-calendar separately and use that. Is probably the way forward, thanks for your help!

Feel free to close this issue, as my question is answered now.
