### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Zunaib** [wojtekmaj/react-datetimerange-picker#15]
Hi, Is there any typescript support.
In case i want to extend your lib's props ?

**Comment by wojtekmaj** [comment]
Hi,
there's none, but there are works to migrate typings to our sibling libraries like React-Date-Picker and React-Date-Picker. Once that's done I believe it should be fairly easy to add support for this one.

**Comment by Zunaib** [comment]
Currently, I've maneuvered my own definitions, i'll keep an eye for the work to be done.

**Comment by Zunaib** [comment]
Can i contribute my index.d.ts file ?
Made it with propTypes and Default Props.

**Comment by wojtekmaj** [comment]
Sure! Typings should be contributed to DefinitelyTyped though, not this repository :)

**Comment by Psvensso** [comment]
Have a look and if you feel like it, approve, this PR.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48743

**Comment by gamegee** [comment]
Hi, I am trying to install the DefinitelyTyped package, but the name does not match the implementation package name. So typescript is not able to resolve the package.

types: `@types/wojtekmaj__react-datetimerange-picker`

implementation: `@wojtekmaj/react-datetimerange-picker`

**Comment by Psvensso** [comment]
@gamegee 
This is correct naming based on convention. As pointed out in the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#what-about-scoped-packages)

**Comment by gamegee** [comment]
Thx @Psvensso I didn't know about it 
I probably need to tweak a bit my tsconfig :)

**Comment by wojtekmaj** [comment]
Closing as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48743 is merged and published.
