### ISSUE TITLE
Nice to have: flag to toggle off the time

### ISSUE THREAD

**Issue by paulincai** [wojtekmaj/react-datetimerange-picker#17]
In order to avoid adding 2 different packages, when necessary in a project, would be nice to be able to switch this package into a daterange-picker with a flag and use both flavors as required.

**Comment by paulincai** [comment]
Ok, that was very easy by using a custom datetime format like ```format='d/MM/y'```

**Comment by wojtekmaj** [comment]
Or use [React-DateRange-Picker](https://github.com/wojtekmaj/react-daterange-picker) ;)

**Comment by paulincai** [comment]
Hi @wojtekmaj,

My point here was for when I need to use two different "flavors" in the same project. For instance on one hand someone creates an event with that and time and on the other hand someone searches for an event in a date range. It would be some overhead to install both packages when a single one could do the job.

**Comment by wojtekmaj** [comment]
I understand, but using React-DateTimeRange-Picker to pick just dates is a misuse of this package. The main reason here is accessibility; in HTML5, there are different native pickers for date and date/time.
