### ISSUE TITLE
Possible to support dark mode?

### ISSUE THREAD

**Issue by li-zhao-hotstar** [wojtekmaj/react-datetimerange-picker#244]
<img width="358" alt="Screenshot 2024-08-14 at 20 01 00" src="https://github.com/user-attachments/assets/83923c3e-b8f2-43b5-851e-93d26b5750e9">

search docs / issues / prs, no mention of dark mode support

**Comment by wojtekmaj** [comment]
You can write your own CSS of course. You don't need to use the included one :)
