### ISSUE TITLE
rangeDivider feature not released

### ISSUE THREAD

**Issue by leoavelino** [wojtekmaj/react-datetimerange-picker#26]
Hi, I have a question: when are you planning to release a new version? I am interested in the `rangeDivider` props feature as shown in the README.

I saw that the feature was added in this commit https://github.com/wojtekmaj/react-datetimerange-picker/commit/4b96e96cc1293f531a2771aa0940a77d8083be44 but the latest release was a month before that

**Comment by wojtekmaj** [comment]
Hm, no idea why I didn't release it 🤔 Thanks for the heads up. Released v3.0.0.
