### ISSUE TITLE
UTC Universal time rather than local?

### ISSUE THREAD

**Issue by moranbw** [wojtekmaj/react-datetimerange-picker#3]
Is it possible to display UTC universal time rather than local time zone?  I'm attempting to pass in my date: like this:

new Date(Date.UTC(2018,3,27,17,5))

It doesn't seem to be honoring the UTC, though, and appears to be converting to my time zone.  Any tips?

**Comment by wojtekmaj** [comment]
Hi,
You would need to manually convert the hour in and out. `Date` has methods like getHours, setHours, getUTCHours, and so on. So you can read local year, month, ..., second, and set it as UTC year, UTC month, ... UTC second on a new `Date` object.
