### ISSUE TITLE
Order of date and time sub-components

### ISSUE THREAD

**Issue by gamegee** [wojtekmaj/react-datetimerange-picker#37]
Hi, it is more a question than a real issue.

I want to change the sub-components ordering, would like to have the following:

```tsx
<StartDate> <StartHour> <EndHour> <EndDate>
```

current order:
```tsx
<StartDate> <StartHour> <EndDate> <EndHour>
```

Not sure how to do this without using lots of flex order, or absolute positioning 🤔

**Comment by wojtekmaj** [comment]
Use `format` prop for custom order of inputs. More on that prop in README.
