### ISSUE TITLE
On Change not returning AM and PM while using custom format

### ISSUE THREAD

**Issue by muhammadhassan149** [wojtekmaj/react-datetimerange-picker#39]
On value change, the value is only returning 12:00 or 11:00 rather than 12:00PM and 11:00PM

**Comment by muhammadhassan149** [comment]
<TimeRangePicker
                amPmAriaLabel="Select AM/PM"
                format="HH:mm a"
                locale={locale}
                onChange={(v) => {
                    setFieldTouched(name, true);
                    setFieldValue(name, v);
                }}
                value={values[name]}
            />

**Comment by wojtekmaj** [comment]
This is expected. JavaScript in general doesn't operate on other time formats than military.
