### ISSUE TITLE
Entering random values in inputs

### ISSUE THREAD

**Issue by takekaratul** [wojtekmaj/react-datetimerange-picker#4]
<img width="1437" alt="Screen Shot 2019-04-23 at 1 55 54 PM" src="https://user-images.githubusercontent.com/29499901/56604279-9ab99500-65cf-11e9-97eb-6d037267031c.png">

**Comment by wojtekmaj** [comment]
Related to wojtekmaj/react-date-picker#128

**Comment by AndrewDir** [comment]
Hello! Can I get an error from the component about incorrectly entered data to display an error message?

**Comment by wojtekmaj** [comment]
You can listen for a bubbling `onInvalid` event.

**Comment by chiahsoon** [comment]
@wojtekmaj Hey, not sure if this is the right avenue to ask but could you slightly flesh-out how would one listen for the `onInvalid` event, or perhaps point to another site that shows how to do it? 

Thank you!
