### ISSUE TITLE
Typescript Error with v3.2

### ISSUE THREAD

**Issue by jingoldby** [wojtekmaj/react-datetimerange-picker#41]
Thanks for the upgrade and fix on the leading zero bug!

Just noticing that since updating we are getting a type error whenever you type a value (rather than clicking in the calendar).

You can confirm this for yourself by looking in the console in [this codesandbox](https://codesandbox.io/s/pyf2j) as you perform each action (change with calendar = no error, change by typing value = error)

Appreciate any insight on this.

**Comment by wojtekmaj** [comment]
I don't think that's a TypeScript error. Fixed in e1c412eb086a801625d6bd60dcfcb2c285193cad.
