### ISSUE TITLE
Doesn't work with NEXT JS

### ISSUE THREAD

**Issue by nilavrusty** [wojtekmaj/react-datetimerange-picker#45]
./node_modules/@wojtekmaj/react-datetimerange-picker/dist/DateTimeRangePicker.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@wojtekmaj/react-datetimerange-picker/dist/entry.js

**Comment by wojtekmaj** [comment]
Use entry.nostyle (see README) and import the styles yourself.

**Comment by nilavrusty** [comment]
Thank you
