### ISSUE TITLE
DateRangePicker does not behave correctly on Safari.

### ISSUE THREAD

**Issue by rythm-of-the-red-man** [wojtekmaj/react-datetimerange-picker#48]
Hi guys I hope you are well!

One of our QAs detected the strange behavior of DateRangePicker on the safari browser. When you use the regular calendar icon it does work properly, but it does not when the user focuses on the widget.  In the second case, it opens the calendar, but it disappears after a click. 
In codebase we have styled DateRangePicker, but changing it to default one does not make any difference:

```jsx
          <StyledDateTimeRangePicker
            onChange={setValidatedTimeRange}
            value={timeRange}
            disableClock
            format="y-MM-dd"
          />
```
I bypassed the problem by using `openWidgetsOnFocus={false}` as it behaves correctly when the user uses the calendar button.
We use `react` 16.8.6 and  `react-datetimerange-picker` in version `3.4.2`. I attach the bug recording below. It does not throw any error in the developer console.

https://user-images.githubusercontent.com/37937186/136739889-9a2b0f34-e2fd-4985-9d5a-03bc8de16a88.mov

Regards,
Mateusz.

**Comment by iba-1** [comment]
I can confirm it's still happening

**Comment by wojtekmaj** [comment]
Potentially related? https://github.com/wojtekmaj/react-date-picker/issues/274
