### ISSUE TITLE
select range includes disabled dates

### ISSUE THREAD

**Issue by performautodev** [wojtekmaj/react-datetimerange-picker#50]
Hello,

How prevent user from select range includes disabled dates, this maybe issue ?
![Screenshot from 2021-11-04 10-26-10](https://user-images.githubusercontent.com/62381545/140289906-5e6f094c-23cf-440b-922d-28e91e0cb9af.png)

**Comment by wojtekmaj** [comment]
While it's possible to disable certain dates in the calendar itself by using tileDisabled prop, the input only supports min and max values. Unfortunately I don't see how this could work with dates disabled selectively.
