### ISSUE TITLE
Logo proposal for react-datetimerange-picker

### ISSUE THREAD

**Issue by memoryskull** [wojtekmaj/react-datetimerange-picker#7]
Hi @wojtekmaj  I love this project
I'm interested in collaborating with this project by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by wojtekmaj** [comment]
Hi! I appreciate your offer. I must disappoint you though, because I already have a graphic designer responsible for identity and illustrations on [our home page](http://projects.wojtekmaj.pl/react-datetimerange-picker/).

**Comment by memoryskull** [comment]
ok perfect @wojtekmaj 
Thank you for your time.
