### ISSUE TITLE
time elapsed calculation

### ISSUE THREAD

**Issue by davidkutas** [wojtekmaj/react-datetimerange-picker#9]
when you use the picker and input a range, does it calculate how much time has elapsed between the finish and start date and time?

**Comment by wojtekmaj** [comment]
No, why would it? React-DateTimeRange-Picker returns an array of dates. You can do anything you want with them - for example:

```js
function onChange([startDate, endDate]) {
  console.log(`Time elapsed: ${endDate - startDate}`);
}
```
