### ISSUE TITLE
Manually Setting Date and Time (Input By Input)

### ISSUE THREAD

**Issue by Ekeu** [wojtekmaj/react-datetimerange-picker#96]
Hello 👋🏽

While working on a project, and using the date-time range picker I noticed some issues with the library 🐛

1. If you fill in the date and the time manually input by input, `onChange` is not called
2. The `onChange` method is called only when you set the `AM/PM` of one of the dates
3. And once you do that the other date is set to `null`
4. Now, if you start changing for example the time of the date, the date that was set to `null` (step 3) becomes a `string`
5. And if you start changing the `AM/PM` of one of the dates the other becomes a `string` and so on...

Below is a video of what I'm trying to explain

https://user-images.githubusercontent.com/23312714/200801632-da30d499-a1d6-4fe9-8177-649ff3e669a8.mov

**Comment by wojtekmaj** [comment]
`onChange` is not called until a complete, valid date is provided. This is consistent with native `<input>` elements.
